# Fichier de configuration pour le déploiement sur Netlify
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Commande pour construire le projet Next.js
  command = "npm run build"
  # Dossier contenant le build final
  publish = ".next"

# Indique à Netlify de chercher les fonctions dans un répertoire qui n'existe pas.
# Ceci empêche Netlify de détecter et d'essayer de construire le dossier `functions`
# qui est destiné à Firebase et non à Netlify, ce qui corrige l'erreur de déploiement.
functions = "netlify/functions"

[[plugins]]
  # Plugin essentiel pour assurer la compatibilité de toutes les fonctionnalités de Next.js
  # (App Router, Server Actions, etc.) avec Netlify.
  package = "@netlify/plugin-nextjs"
